//+------------------------------------------------------------------+
//|                                              TradeCopier.mq5     |
//|                  MT5 Local Trade Copier (Master / Slave)         |
//+------------------------------------------------------------------+
#property copyright "Generated by Claude"
#property version   "1.00"
#property strict

#include <TradeCopier\CopierConfig.mqh>
#include <TradeCopier\MasterPublisher.mqh>
#include <TradeCopier\SlaveSubscriber.mqh>

CMasterPublisher g_master;
CSlaveSubscriber g_slave;

//+------------------------------------------------------------------+
int OnInit()
{
   if(CopierMode == COPIER_MASTER)
   {
      if(!g_master.Init(SharedDataPath, HeartbeatSeconds))
      {
         Print("TradeCopier: failed to initialize MASTER");
         return INIT_FAILED;
      }
      EventSetMillisecondTimer(MasterSnapshotIntervalMs);
      Print("TradeCopier: running as MASTER");
   }
   else
   {
      if(!g_slave.Init(SharedDataPath, SymbolMap, MaxTradeAgeMinutes, RetryCount, RetryDelayMs, HeartbeatSeconds))
      {
         Print("TradeCopier: failed to initialize SLAVE");
         return INIT_FAILED;
      }
      EventSetMillisecondTimer(SlavePollIntervalMs);
      Print("TradeCopier: running as SLAVE");
   }
   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
   EventKillTimer();
   if(CopierMode == COPIER_MASTER)
      g_master.Deinit();
   else
      g_slave.Deinit();
   Print("TradeCopier: stopped");
}

//+------------------------------------------------------------------+
void OnTick()
{
   // work is done in OnTimer for both modes
}

//+------------------------------------------------------------------+
void OnTimer()
{
   if(CopierMode == COPIER_MASTER)
      g_master.PublishChanges(MasterSnapshotIntervalMs);
   else
      g_slave.Poll();
}

//+------------------------------------------------------------------+
